### ISSUE TITLE
Error reading image, where can I download the material?

### ISSUE THREAD

**Issue by DapengFeng** [TomClabault/HIPRT-Path-Tracer#7]
Hi, @TomClabault . I tried to run the program `./HIPRTPathTracer` but got a `Segmentation fault (core dumped)`. Is it any tip to execute the program correctly?
```
Reading scene file ../data/GLTFs/the-white-room-low.gltf ...
Scene geometry parsed in 106ms
Reading "" envmap...
Error reading image 
hiprt ver.02004
Executing on 'NVIDIA GeForce RTX 4090'
Empty envmap set on the GPURenderer... Defaulting to uniform ambient light type
Compiling BVH building kernels & building scene SBVH


Kernel "CameraRays" compiled in 16021ms. 
	128 registers.
	12288 shared memory.
	248 local memory.

Kernel "ReSTIR_DI_LightsPresampling" compiled in 245ms. 
	32 registers.
	0 shared memory.
	0 local memory.

Kernel "ReSTIR_DI_InitialCandidates" compiled in 754ms. 
	151 registers.
	4096 shared memory.
	48 local memory.
../src/Device/kernels/ReSTIR/DI/TemporalReuse.h(150): warning #550-D: variable "selected_neighbor" was set but never used
  	int selected_neighbor = 0;
  	    ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"


Kernel "ReSTIR_DI_TemporalReuse" compiled in 3952ms. 
	154 registers.
	4096 shared memory.
	48 local memory.

Kernel "FullPathTracer" compiled in 2322ms. 
	233 registers.
	12288 shared memory.
	320 local memory.
../src/Device/includes/ReSTIR/DI/SpatiotemporalMISWeight.h(127): warning #177-D: variable "reused_neighbors_count" was declared but never referenced
  		int reused_neighbors_count = render_data.render_settings.restir_di_settings.spatial_pass.spatial_reuse_neighbor_count;
  		    ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

../src/Device/includes/ReSTIR/DI/SpatiotemporalMISWeight.h(202): warning #177-D: variable "reused_neighbors_count" was declared but never referenced
  		int reused_neighbors_count = render_data.render_settings.restir_di_settings.spatial_pass.spatial_reuse_neighbor_count;
  		    ^

../src/Device/includes/ReSTIR/DI/SpatiotemporalNormalizationWeight.h(73): warning #177-D: variable "neighbor_reservoir" was declared but never referenced
  			ReSTIRDIReservoir neighbor_reservoir = render_data.render_settings.restir_di_settings.spatial_pass.input_reservoirs[neighbor_pixel_index];
  			                  ^

../src/Device/kernels/ReSTIR/DI/FusedSpatiotemporalReuse.h(213): warning #550-D: variable "selected_neighbor" was set but never used
  	int selected_neighbor = 0;
  	    ^


Kernel "ReSTIR_DI_SpatiotemporalReuse" compiled in 1333ms. 
	219 registers.
	6144 shared memory.
	96 local memory.
../src/Device/includes/ReSTIR/DI/SpatialMISWeight.h(101): warning #177-D: variable "reused_neighbors_count" was declared but never referenced
  		int reused_neighbors_count = render_data.render_settings.restir_di_settings.spatial_pass.spatial_reuse_neighbor_count;
  		    ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

../src/Device/includes/ReSTIR/DI/SpatialMISWeight.h(177): warning #177-D: variable "reused_neighbors_count" was declared but never referenced
  		int reused_neighbors_count = render_data.render_settings.restir_di_settings.spatial_pass.spatial_reuse_neighbor_count;
  		    ^

../src/Device/kernels/ReSTIR/DI/SpatialReuse.h(138): warning #550-D: variable "selected_neighbor" was set but never used
  	int selected_neighbor = 0;
  	    ^


Kernel "ReSTIR_DI_SpatialReuse" compiled in 824ms. 
	168 registers.
	2048 shared memory.
	64 local memory.
BVH built in 25664ms
Full scene parsed & built in 26239ms
Scene statistics: 
	187101 vertices
	247107 vertices
	8 emissive triangles
	53 materials
	16 textures
Segmentation fault (core dumped)
```

**Comment by TomClabault** [comment]
Hi @DapengFeng , thanks for the report!

The console warning
```
Reading "" envmap...
Error reading image 
```
isn't actually an error. I should remove this warning. It is misleading. This just means that there will be no environment map but this is not an error.

I don't immediately see where the segfault could come from, could try running the app with `gdb ./HIPRTPathTracer` and see where the segfault occurs?

**Comment by DapengFeng** [comment]
Thanks for your advice. The callback is listed below.
```
Thread 352 "HIPRTPathTracer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbb400640 (LWP 1919435)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555558945dd in oroEventCreate (event=0x7fffbb3ff9f8) at /home/dapeng/HIPRT-Path-Tracer/thirdparties/Orochi-Fork/Orochi/Orochi.cpp:1633
#2  0x0000555555688474 in GPUKernel::GPUKernel (this=0x7fffbb3ff9b0) at /home/dapeng/HIPRT-Path-Tracer/src/Compiler/GPUKernel.cpp:25
#3  0x0000555555688597 in GPUKernel::GPUKernel (this=0x7fffbb3ff9b0, kernel_file_path="../src/Device/kernels/CameraRays.h", kernel_function_name="CameraRays") at /home/dapeng/HIPRT-Path-Tracer/src/Compiler/GPUKernel.cpp:29
#4  0x0000555555750f0c in ThreadFunctions::precompile_kernel (kernel_function_name="CameraRays", kernel_filepath="../src/Device/kernels/CameraRays.h", options=..., hiprt_ctx=std::shared_ptr<HIPRTOrochiCtx> (use count 5, weak count 0) = {...}, func_name_sets=std::vector of length 1, capacity 1 = {...}) at /home/dapeng/HIPRT-Path-Tracer/src/Threads/ThreadFunctions.cpp:22
#5  0x0000555555727e97 in std::__invoke_impl<void, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::reference_wrapper<std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > > > (
    __f=@0x555559854988: 0x555555750eaa <ThreadFunctions::precompile_kernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&)>)
    at /usr/include/c++/11/bits/invoke.h:61
#6  0x00005555557279ca in std::__invoke<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::reference_wrapper<std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > > > (
    __fn=@0x555559854988: 0x555555750eaa <ThreadFunctions::precompile_kernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&)>)
    at /usr/include/c++/11/bits/invoke.h:96
#7  0x000055555572767f in std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::reference_wrapper<std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > > > >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul, 5ul> (this=0x5555598548a8) at /usr/include/c++/11/bits/std_thread.h:259
#8  0x0000555555727480 in std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::reference_wrapper<std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > > > >::operator() (this=0x5555598548a8) at /usr/include/c++/11/bits/std_thread.h:266
#9  0x00005555557272f4 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, GPUKernelCompilerOptions, std::shared_ptr<HIPRTOrochiCtx>, std::reference_wrapper<std::vector<hiprtFuncNameSet, std::allocator<hiprtFuncNameSet> > > > > >::_M_run (this=0x5555598548a0) at /usr/include/c++/11/bits/std_thread.h:211
#10 0x00007ffff76dc253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7294ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#12 0x00007ffff7326850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by TomClabault** [comment]
Alright, that's a bug that I had fixed on my dev branch but that I hadn't merged to main yet.

Could you pull and try again? I modified some git submodules so you'll have to run these commands, not just git pull:

```
cd build
git pull --rebase
rm -rf ../thirdparties/imgui
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=Debug

<build with Ninja/Make/...>

/HIPRTPathTracer
```

Does that fix the segfault?

**Comment by DapengFeng** [comment]
It works for me, but it still lacks some header files. I created a pull request #8 to fix this.

**Comment by TomClabault** [comment]
Great, thanks for the PR!

If you have any feedback/ideas on the application, I'd love to hear it so do not hesitate ;)

**Comment by DapengFeng** [comment]
Let’s  keep in touch!:)
